/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientui;

import client.AudioSpeakerClient;

/**
 *
 * @author stuar
 */
public class AudioSpeakerGUI extends javax.swing.JFrame {

    private AudioSpeakerClient client;
    /**
     * Creates new form AudioSpeakerGUI
     */
    public AudioSpeakerGUI() {
        initComponents();
    }

    public AudioSpeakerGUI(AudioSpeakerClient aThis) {
        this();
        this.client = aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTA = new javax.swing.JTextArea();
        speakerShutdownBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Audio Speaker");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("Status");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        statusTA.setColumns(20);
        statusTA.setRows(5);
        statusTA.setText("OFF");
        jScrollPane1.setViewportView(statusTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 66, 330, 320));

        speakerShutdownBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        speakerShutdownBtn.setForeground(new java.awt.Color(255, 51, 0));
        speakerShutdownBtn.setText("Shut down");
        speakerShutdownBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speakerShutdownBtnActionPerformed(evt);
            }
        });
        getContentPane().add(speakerShutdownBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void speakerShutdownBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speakerShutdownBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speakerShutdownBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AudioSpeakerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AudioSpeakerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AudioSpeakerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AudioSpeakerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AudioSpeakerGUI().setVisible(true);
            }
        });
    }

    public void appendAudioSpeakerStatus(String toString) {
        statusTA.setText(toString);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton speakerShutdownBtn;
    private javax.swing.JTextArea statusTA;
    // End of variables declaration//GEN-END:variables
}
