/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientui;

import client.ControlPanelClient;
import client.ProjectorClient;
import java.util.logging.Level;
import java.util.logging.Logger;
import services.ProjectorServer;

/**
 *
 * @author stuar
 */
public class ControlPanelGUI extends javax.swing.JFrame {
    
    private ControlPanelClient client;
    private String machine = "";

    /**
     * Creates new form NewJFrame
     */
    public ControlPanelGUI() {
        initComponents();
        
    }

    public ControlPanelGUI(ControlPanelClient aThis) throws Exception {
         this();
         this.client = aThis;
         projectorTA.setText("Not connected");
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setInputMachineBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        speakersActivateBtn = new javax.swing.JButton();
        videoActivateBtn = new javax.swing.JButton();
        thermoActivateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        projActivateBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        videoTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        projectorTA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputMachineTA = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        speakersTA = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        thermoTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setInputMachineBtn.setText("Set Machine");
        setInputMachineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setInputMachineBtnActionPerformed(evt);
            }
        });
        getContentPane().add(setInputMachineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        jLabel1.setText("Control Panel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 16, -1, -1));

        speakersActivateBtn.setText("Activate");
        speakersActivateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speakersActivateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(speakersActivateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 237, 102, -1));

        videoActivateBtn.setText("Activate");
        videoActivateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoActivateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(videoActivateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 488, -1, -1));

        thermoActivateBtn.setText("Activate");
        thermoActivateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thermoActivateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(thermoActivateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 488, 105, -1));

        jLabel2.setText("Choose Input Machine");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("Projector");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        projActivateBtn.setText("Activate");
        projActivateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projActivateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(projActivateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jLabel4.setText("Video-camera");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 492, -1, -1));

        jLabel5.setText("Thermostat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 492, -1, -1));

        jLabel6.setText("Speakers");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 241, -1, -1));

        videoTA.setColumns(20);
        videoTA.setRows(5);
        jScrollPane1.setViewportView(videoTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 526, 220, -1));

        projectorTA.setColumns(20);
        projectorTA.setRows(5);
        jScrollPane2.setViewportView(projectorTA);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 220, -1));

        inputMachineTA.setColumns(20);
        inputMachineTA.setRows(5);
        jScrollPane3.setViewportView(inputMachineTA);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 210, 100));

        speakersTA.setColumns(20);
        speakersTA.setRows(5);
        jScrollPane4.setViewportView(speakersTA);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 230, -1));

        thermoTA.setColumns(20);
        thermoTA.setRows(5);
        jScrollPane5.setViewportView(thermoTA);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setInputMachineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setInputMachineBtnActionPerformed
        inputMachineTA.append("Success! Control panel connected to: " + this.machine);
    }//GEN-LAST:event_setInputMachineBtnActionPerformed

    private void projActivateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projActivateBtnActionPerformed
        // activate projector client
        try{
            Thread.sleep(3000);
        }catch(Exception e){
            System.out.println(e);
        }
        ProjectorClient.main(null);
        projectorTA.setText("Projector activated and connected to: " + this.machine);
    }//GEN-LAST:event_projActivateBtnActionPerformed

    private void videoActivateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoActivateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_videoActivateBtnActionPerformed

    private void speakersActivateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speakersActivateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speakersActivateBtnActionPerformed

    private void thermoActivateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thermoActivateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thermoActivateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPanelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPanelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPanelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPanelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPanelGUI().setVisible(true);
            }
        });
    }
    
    public void appendDetectedMachine(String machineIP){
        inputMachineTA.append(machineIP);
        this.machine = machineIP;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea inputMachineTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton projActivateBtn;
    private javax.swing.JTextArea projectorTA;
    private javax.swing.JButton setInputMachineBtn;
    private javax.swing.JButton speakersActivateBtn;
    private javax.swing.JTextArea speakersTA;
    private javax.swing.JButton thermoActivateBtn;
    private javax.swing.JTextArea thermoTA;
    private javax.swing.JButton videoActivateBtn;
    private javax.swing.JTextArea videoTA;
    // End of variables declaration//GEN-END:variables


}
