/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientui;

import client.ProjectorClient;

/**
 *
 * @author stuar
 */
public class ProjectorGUI extends javax.swing.JFrame {

    private ProjectorClient client;

    /**
     * Creates new form ProjectorGUI
     */
    public ProjectorGUI() {
        initComponents();
    }

    public ProjectorGUI(ProjectorClient aThis) {
        this();
        this.client = aThis;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTF = new javax.swing.JTextArea();
        projShutdownBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Projector");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Status");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        statusTF.setColumns(20);
        statusTF.setRows(5);
        statusTF.setText("OFF");
        jScrollPane1.setViewportView(statusTF);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 54, 280, 290));

        projShutdownBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        projShutdownBtn.setForeground(new java.awt.Color(255, 51, 0));
        projShutdownBtn.setText("Shut down");
        projShutdownBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projShutdownBtnActionPerformed(evt);
            }
        });
        getContentPane().add(projShutdownBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 370, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projShutdownBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projShutdownBtnActionPerformed
        close();
    }//GEN-LAST:event_projShutdownBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectorGUI().setVisible(true);
            }
        });
    }
    
    public void close(){
        this.setVisible(false);
    }

    public void appendProjectorStatus(String toString) {
        statusTF.append("\n" + toString + "\n");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton projShutdownBtn;
    private javax.swing.JTextArea statusTF;
    // End of variables declaration//GEN-END:variables
}
