/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientui;

import client.ThermostatClient;

/**
 *
 * @author stuar
 */
public class ThermostatGUI extends javax.swing.JFrame {

    private ThermostatClient client;

    /**
     * Creates new form ThermostatGUI
     */
    public ThermostatGUI() {
        initComponents();
    }

    public ThermostatGUI(ThermostatClient aThis) {
        this();
        this.client = aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        thermoStatusTA = new javax.swing.JTextArea();
        thermoShutdownBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Thermostat");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("Status");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        thermoStatusTA.setColumns(20);
        thermoStatusTA.setRows(5);
        thermoStatusTA.setText("OFF\n");
        jScrollPane1.setViewportView(thermoStatusTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 67, 300, 330));

        thermoShutdownBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        thermoShutdownBtn.setForeground(new java.awt.Color(255, 51, 0));
        thermoShutdownBtn.setText("Shut down");
        thermoShutdownBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thermoShutdownBtnActionPerformed(evt);
            }
        });
        getContentPane().add(thermoShutdownBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 420, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thermoShutdownBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thermoShutdownBtnActionPerformed
        close();
    }//GEN-LAST:event_thermoShutdownBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThermostatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThermostatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThermostatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThermostatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThermostatGUI().setVisible(true);
            }
        });
    }

    public void appendThermostatStatus(String toString) {
        thermoStatusTA.setText(toString);
    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton thermoShutdownBtn;
    private javax.swing.JTextArea thermoStatusTA;
    // End of variables declaration//GEN-END:variables

    public void close() {
        this.setVisible(false);
    }
}
